get_filename_component(OPENHOBBYOS_ROOT "${CMAKE_CURRENT_LIST_DIR}/../.." ABSOLUTE)
set(OPENHOBBYOS_USER_LD "${OPENHOBBYOS_ROOT}/user.ld" CACHE FILEPATH "OpenHobbyOS user linker script")

set(OPENHOBBYOS_TARGET "i686-openhobbyos" CACHE STRING "OpenHobbyOS cross target")
set(OPENHOBBYOS_SYSROOT "${OPENHOBBYOS_ROOT}/build/ports/sysroot" CACHE PATH "OpenHobbyOS sysroot")

set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR i686)
set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(CMAKE_SYSROOT "${OPENHOBBYOS_SYSROOT}")
set(CMAKE_C_COMPILER "${OPENHOBBYOS_TARGET}-gcc")
set(CMAKE_AR "${OPENHOBBYOS_TARGET}-ar")
set(CMAKE_RANLIB "${OPENHOBBYOS_TARGET}-ranlib")
set(CMAKE_STRIP "${OPENHOBBYOS_TARGET}-strip")
set(PKG_CONFIG_EXECUTABLE "${OPENHOBBYOS_TARGET}-pkg-config")

set(CMAKE_FIND_ROOT_PATH "${OPENHOBBYOS_SYSROOT}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(CMAKE_C_FLAGS_INIT "-O2 -D_GNU_SOURCE -D_DEFAULT_SOURCE -D_XOPEN_SOURCE=700 -D_POSIX_C_SOURCE=200809L -D_POSIX_TIMERS=200809L -D_POSIX_MONOTONIC_CLOCK=200809L -D_POSIX_CLOCK_SELECTION=200809L -Wno-char-subscripts")
set(CMAKE_EXE_LINKER_FLAGS_INIT "--sysroot=${OPENHOBBYOS_SYSROOT} -static -Wl,-T,${OPENHOBBYOS_USER_LD} -nostartfiles -lopenhobbyosgloss")
