#ifndef OPENHOBBYOS_LINUX_IF_ADDR_H
#define OPENHOBBYOS_LINUX_IF_ADDR_H

#define IFA_F_SECONDARY  0x01
#define IFA_F_TEMPORARY  IFA_F_SECONDARY
#define IFA_F_OPTIMISTIC 0x04
#define IFA_F_DADFAILED  0x08
#define IFA_F_DEPRECATED 0x20
#define IFA_F_TENTATIVE  0x40

#endif
